### PR TITLE
Reporting Process Update

### PR DESCRIPTION
**Pull request by annalee**
Hey folks, the current reporting process is massively out of date. @JenTress and I banged out some new language that explains the reporting process as it currently exists. I recognize we might want to have a separate conversation about improving the reporting process overall, but for this PR I'm only concerned with making the language reflect our current reality.

Per the policy in CONTRIBUTING.md, this pull request needs to be open for at least seven days, and needs to get a 👍  from "a majority of members of the code of conduct working group that have opted into the conversation." At this point, the CoC working group is a subcommittee of the Diversity Guild. And of course, everyone in 18F should feel free to weigh in, whether or not you consider yourself part of the guild.

### CODE REVIEW

**Comment by wslack** [comment]
LGTM; thank you Annalee! :+1:

**Comment by leahbannon** [comment]
This LGTM. I'd like to also add something telling folks that the #g-diversity and #wg-code-of-conduct slack channels are spaces that are happy to help advise. I know we need to be careful not to make it seem like those are official alternatives for resolving an issue, and we would need to make sure that folks in the channel know they need to encourage folks to basically follow the paths that you've outlined in this pull request, but I worry that it is so common for folks to feel unsure that theit experience rises to the level of mistreatment that should be reported to their supervisor (even though it often is) and consequently they stay silent. Reminding folks that those groups are happy to help could be a way to make folks feel more comfortable about speaking up. This would also support one of our (draft) OKRs, "In surveys, at least 80% of 18F team says they regard the diversity guild as reliable advisors on diversity and inclusion (including language and processes)."

Perhaps we could add something like, "If you have any questions about this, the Diversity Guild and the Code of Conduct Working Group members are also happy to help. You can find them on slack at #g-diversity and #wg-code-of-conduct or reach out to members directly."

**Comment by annalee** [comment]
@leahbannon and I discussed this offline--we're going to work on a second pull request to make sure folks know they can come to the guild for assistance and support when they're trying to decide if they want to make a report.

**Comment by NoahKunin** [comment]
@annalee Looks great! This is now creating some discordance with our Slack guidelines, and I'd love to permalink to the correct guidance ASAP. I'll poke the Slack channel to ensure that as soon as the 7 day threshold is hit, we have enough votes.

**Comment by wslack** [comment]
Merging per @annalee.

**Pull request merged**
